// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PonudeApp.Infrastructure.EntityFrameworkCore;

#nullable disable

namespace PonudeApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PonudeApp.Domain.Entities.Ponuda", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BrojPonude")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrojPonude"));

                    b.Property<DateTime>("DatumPonude")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Ponude");
                });

            modelBuilder.Entity("PonudeApp.Domain.Entities.PonudaStavka", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Artikl")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal>("JedinicnaCijena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Kolicina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<Guid>("PonudaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PonudaId");

                    b.ToTable("PonudaStavke");
                });

            modelBuilder.Entity("PonudeApp.Domain.Entities.PonudaStavka", b =>
                {
                    b.HasOne("PonudeApp.Domain.Entities.Ponuda", "Ponuda")
                        .WithMany("Stavke")
                        .HasForeignKey("PonudaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ponuda");
                });

            modelBuilder.Entity("PonudeApp.Domain.Entities.Ponuda", b =>
                {
                    b.Navigation("Stavke");
                });
#pragma warning restore 612, 618
        }
    }
}
